DROP TABLE IF EXISTS `part`;CREATE TABLE `part` (
  `ID` char(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'md5(PartNumber+SupplierCode+LocationID)',
  `Cmf` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'Dealership Code',
  `PartNumber` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'first in ID',
  `SupplierCode` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'second in ID -> MfgCode',
  `LocationID` int(10) unsigned NOT NULL COMMENT 'third in ID',
  `Description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `DisplayText` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `OnHand` int(11) DEFAULT 0,
  `Avail` int(11) DEFAULT 0,
  `OnOrder` int(11) DEFAULT 0,
  `Cost` double(11,2) DEFAULT 0.00,
  `MSRP` double(11,2) DEFAULT 0.00,
  `Bin1` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `Bin2` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `Bin3` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `Weight` double(11,3) DEFAULT 0.000,
  `Length` double(11,2) DEFAULT 0.00,
  `Depth` double(11,2) DEFAULT 0.00,
  `Height` double(11,2) DEFAULT 0.00,
  `Upc` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `Asin` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `Disappear` tinyint(1) DEFAULT 0 COMMENT 'bool flag Disappear set to 1 if Avail=0',
  `UpdatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID`),
  KEY `PartNumber` (`PartNumber`) USING BTREE,
  KEY `SupplierCode` (`SupplierCode`) USING BTREE,
  KEY `LocationID` (`LocationID`) USING BTREE,
  KEY `part_mult` (`PartNumber`,`SupplierCode`,`LocationID`) USING BTREE,
  KEY `sku` (`SupplierCode`,`PartNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci