DROP TABLE IF EXISTS `partlog`;CREATE TABLE `partlog` (
  `ID` char(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'md5(PartNumber+SupplierCode+LocationID)',
  `Cmf` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'Dealership Code',
  `PartNumber` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'first in ID',
  `SupplierCode` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'second in ID -> MfgCode',
  `LocationID` int(10) unsigned NOT NULL COMMENT 'third in ID',
  `Avail` int(11) DEFAULT 0,
  `OnOrder` int(11) DEFAULT 0,
  `Cost` double(11,2) DEFAULT 0.00,
  `MSRP` double(11,2) DEFAULT 0.00,
  `Bin1` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT '',
  `ScopeAvail` tinyint(1) DEFAULT 0,
  `ScopeOnOrder` tinyint(1) DEFAULT 0,
  `ScopeCost` tinyint(1) DEFAULT 0,
  `ScopeMSRP` tinyint(1) DEFAULT 0,
  `ScopeBin1` tinyint(1) DEFAULT 0,
  `UpdatedAt` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  KEY `ID` (`ID`) USING BTREE,
  KEY `PartNumber` (`PartNumber`) USING BTREE,
  KEY `SupplierCode` (`SupplierCode`) USING BTREE,
  KEY `LocationID` (`LocationID`) USING BTREE,
  KEY `part_mult` (`PartNumber`,`SupplierCode`,`LocationID`) USING BTREE,
  KEY `sku` (`SupplierCode`,`PartNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci